name: Trigger Build

on:
 push:
  branches:
   - main

jobs:
 call-workflow:
  uses: siddmoitra/centralpipeline/.github/workflows/ci.yml@main
  with:
   repo-name: ${{ github.event.repository.name }}
   branch: ${{ github.head_ref || github.ref_name }}
  secrets: inherit
