## This file holds the workflow dispatcher for the release workflow
name: Trigger Release

on:
 pull_request:
  types:
   - closed
  branches:
   - release/**

jobs:
 test-me:
  name: Yulu
  runs-on: ubuntu-latest
  steps:
   - name: Print GitHub Context
     env:
       GITHUB_CONTEXT: ${{ toJson(github) }}
     run: |
       echo "GitHub Context:"
       echo "${GITHUB_CONTEXT}" | jq '.'
   
