## This file holds the workflow dispatcher for the release workflow
name: Trigger Release

on:
 pull_request:
  types:
   - closed
  branches:
   - 'main'
  paths:
   - 'CHANGELOG.md'

jobs:
 test-me:
  name: Yulu
  runs-on: ubuntu-latest
  steps:
   - name: Print GitHub Context
     if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
     env:
       GITHUB_CONTEXT: ${{ toJson(github) }}
     run: |
       echo "GitHub Context:"
       echo "${GITHUB_CONTEXT}" | jq '.'
   
