## This file holds the workflow dispatcher for the release workflow
name: Trigger Release

on:
 push:
  branches:
   - main

jobs:
 test-me:
  name: Yulu
  runs-on: ubuntu-latest
  steps:
   - name: Pretty Print GitHub Context
     uses: actions/github-script@v6
     with:
       script: |
         console.log('GitHub Context:')
         console.log(JSON.stringify(github, null, 2))
   
